In [1]:
import numpy as np

In [2]:
x=np.array([[0,0],[0,1],[1,0],[1,1]])
y=np.array([[0,0,0,1]]).T
x.shape,y.shape

((4, 2), (4, 1))

In [3]:
def sigmoid(z):
    return (1/(1+np.exp(-z)))

In [5]:
#no hidden layer weifght
weight=2*np.random.random((2,1))-1
bias=2*np.random.random(1)-1
weight

array([[-0.98961687],
       [-0.31023409]])

In [6]:
output0=x
output=sigmoid(np.dot(output0,weight)+bias)
output

array([[0.3664715 ],
       [0.29783719],
       [0.17697165],
       [0.13619784]])

In [7]:
#hidden layer is wh and wo is the weight
#for the output layer
wh=2*np.random.random((2,2))-1# herre first two is because the training feature are 2 and 2nd 2 is because the 2 hidden layers in 
wo=2*np.random.random((2,1))-1# here 2 is no. of output in hidden layer

In [8]:
wh,wo

(array([[-0.58673499,  0.35839812],
        [ 0.56501206,  0.49502658]]),
 array([[0.6618502 ],
        [0.22238598]]))

In [9]:
bh=2*np.random.random((1,2))-1

In [10]:
bh

array([[-0.58856961,  0.32176378]])

In [12]:
bo=2*np.random.random(1)-1
bo

array([-0.3748217])

In [13]:
outputhidden=sigmoid(np.dot(x,wh)+bh) 
outputfinal=sigmoid(np.dot(outputhidden,wo)+bo)
outputfinal

array([[0.49759091],
       [0.52658553],
       [0.48223781],
       [0.50701594]])