In [1]:
import numpy as np

In [3]:
x=np.array([[0,0,0],[1,0,0],[1,1,0],[1,1,1]])

In [4]:
wh1=2*np.random.random((3,4))-1
b1=2*np.random.random((1,4))-1
wo=2*np.random.random((4,1))-1
bo=2*np.random.random(1)-1

In [5]:
wh1,b1,wo,bo

(array([[ 0.3106764 , -0.62668402, -0.1090227 ,  0.64245645],
        [ 0.38520901, -0.19371338,  0.54105345,  0.99910706],
        [ 0.10004468,  0.63788696,  0.75116756,  0.11058944]]),
 array([[-0.77753676,  0.73609132,  0.32298894, -0.33263145]]),
 array([[-0.12729244],
        [ 0.10119942],
        [ 0.42400573],
        [ 0.83476488]]),
 array([0.38228741]))

In [6]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

In [7]:
output_hidden1=sigmoid(np.dot(x,wh1)+b1)

In [8]:
output_hidden1

array([[0.31485101, 0.67614055, 0.58005251, 0.41760049],
       [0.38535962, 0.52732458, 0.55328841, 0.57684255],
       [0.4795985 , 0.47893596, 0.68027148, 0.7873344 ],
       [0.5045982 , 0.63496598, 0.81849547, 0.80526339]])

In [9]:
output_final=sigmoid(np.dot(output_hidden1,wo)+bo)

In [10]:
output_final

array([[0.73207544],
       [0.75077022],
       [0.78841275],
       [0.80243234]])