In [2]:
import numpy as np

In [3]:
x=np.array([[0,0],[0,1],[1,0],[1,1]])
y=np.array([[0,0,0,1]]).T
x.shape,y.shape

((4, 2), (4, 1))

In [4]:
def sigmoid(z):
    return (1/(1+np.exp(-z)))

In [5]:
def derivative_sigmoid(z):
    return sigmoid(z)*(1-sigmoid(z))

In [6]:
weight=2*np.random.random((2,1))-1
bias=2*np.random.random(1)-1
weight

array([[-0.30048324],
       [ 0.16938812]])

In [7]:
output0=x
output=sigmoid(np.dot(output0,weight)+bias)
output

array([[0.62412897],
       [0.66295688],
       [0.55147392],
       [0.59291181]])

In [8]:
#first term =dE/doj
#output=yp
first_term=output-y
second_term=derivative_sigmoid(np.dot(output0,weight)+bias)
first_two=first_term*second_term
first_two.shape

(4, 1)

In [29]:
#now we will create change which will 
#contain dE/dwij
#same as size of weight
change=np.zeros((2,1))
changex,changey=change.shape
changex
len(x)
lr=0.0001

In [36]:
for itr in range(10):    
    change=np.dot(x.T,first_two)
    weight=weight-lr*change
    bias_change=0.0
    # bias change where oi =1
    bias_change=np.sum(first_two)
    bias=bias-lr*bias_change

In [37]:
weight,bias
output=sigmoid(np.dot(x,weight)+bias)

C:\Users\91701\AppData\Local\Temp\ipykernel_5864\826162963.py:2: RuntimeWarning: overflow encountered in exp
  return (1/(1+np.exp(-z)))


In [38]:
output,weight,bias

(array([[1.52044187e-003],
        [3.75282329e-231],
        [8.00662825e-178],
        [0.00000000e+000]]),
 array([[-401.29264414],
        [-524.08741536]]),
 array([-6.48723269]))