In [37]:
import numpy as np

In [38]:
x=np.array([[0,0],[0,1],[1,0],[1,1]])
y=np.array([[0,1,1,0]]).T
x.shape,y.shape

((4, 2), (4, 1))

In [39]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

In [40]:
def derivative(z):
    return sigmoid(z)*(1-sigmoid(z))

In [41]:
wh=2*np.random.random((2,2))-1
bh=2*np.random.random((1,2))-1
wo=2*np.random.random((2,1))-1
bo=2*np.random.random((1,1))-1
lr=0.1

In [42]:
wh

array([[-0.48153106, -0.05053513],
       [ 0.15170033, -0.79690442]])

In [45]:
for itr in range(10000):
    output0=x
    input_hidden=np.dot(output0,wh)+bh
    output_hidden=sigmoid(np.dot(output0,wh)+bh)
    inputForOutput=np.dot(output_hidden,wo)+bo
    output=sigmoid(np.dot(output_hidden,wo)+bo)
    output



    first_term_output=output-y
    second_term_output=derivative(inputForOutput) 
    first_two_output=first_term_output*second_term_output



    first_term_hidden_layer=np.dot(first_two_output,wo.T)
    second_term_hidden_layer=derivative(input_hidden)
    first_two_hidden=first_term_hidden_layer*second_term_hidden_layer 



    changeoutput=np.dot(output_hidden.T,first_two_output)
    changeoutputbias=np.sum(first_two_output,keepdims=True,axis=0)


    changehidden=np.dot(output0.T,first_two_hidden)
    changehiddenbias=np.sum(first_two_hidden,keepdims=True,axis=0)

    w0=wo-lr*changeoutput
    bo=bo-lr*changeoutputbias
    wh=wh-lr*changehidden
    bh=bh-lr*changehiddenbias

In [46]:
output0=x
input_hidden=np.dot(output0,wh)+bh
output_hidden=sigmoid(input_hidden)
inputForOutput=np.dot(output_hidden,wo)+bo
output=sigmoid(inputForOutput)
output,wh,wo,bo,bh




(array([[0.46004341],
        [0.51402285],
        [0.51406303],
        [0.51447281]]),
 array([[-8.61708725,  0.01622351],
        [-8.61712102, -0.80577863]]),
 array([[-0.2230886 ],
        [ 0.00091879]]),
 array([[0.05769239]]),
 array([[ 3.80485932, -0.39416917]]))