In [ ]:
from sklearn import datasets
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
boston=datasets.load_boston()
from sklearn import preprocessing

In [2]:
x=boston.data
y=boston.target

In [3]:
x.shape

(506, 13)

In [5]:
from sklearn import preprocessing
scaler=preprocessing.StandardScaler()


In [6]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y)


In [8]:
xtrain.shape

(379, 13)

In [20]:
xtrain1=scaler.fit(xtrain)
xtrain1=scaler.transform(xtrain)

In [21]:
alg=LinearRegression()

In [22]:
alg.fit(xtrain1,ytrain)

LinearRegression()

In [23]:
xtest=scaler.transform(xtest)

In [25]:
alg.coef_

array([-1.13228491,  1.13297228,  0.16918382,  0.69137181, -1.78812043,
        2.74555157, -0.1560295 , -3.22286476,  3.05906466, -2.23631166,
       -1.91477623,  1.27476942, -3.83533281])

In [26]:
alg.score(xtest,ytest)

0.7092307611943066

In [30]:
xtrain1.std(axis=0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [33]:
scaler2=preprocessing.MinMaxScaler()

In [35]:
xtrain2=scaler2.fit_transform(xtrain)

In [39]:
alg2=LinearRegression()


In [40]:
alg2.fit(xtrain2,ytrain)

LinearRegression()

In [41]:
xtest2=scaler2.transform(xtest)

In [42]:
alg2.score(xtest2,ytest)

-2.1707553381743696

In [43]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y)

In [44]:
xtrain.shape

(379, 13)

In [46]:
xtrain.std(axis=0)

array([9.56641023e+00, 2.38844265e+01, 6.81199699e+00, 2.61573271e-01,
       1.14902093e-01, 7.18747561e-01, 2.80875516e+01, 2.16450033e+00,
       8.66170773e+00, 1.67731350e+02, 2.16947908e+00, 8.73205170e+01,
       7.31923630e+00])

In [47]:
scaler3=preprocessing.MinMaxScaler()

In [48]:
alg3=LinearRegression()

In [49]:
scaler3.fit(xtrain)

MinMaxScaler()

In [50]:
xtrain4=scaler3.transform(xtrain)

In [52]:
xtrain4[0]

array([0.01174445, 0.        , 0.28152493, 0.        , 0.30480167,
       0.45972115, 0.27188465, 0.30635906, 0.13043478, 0.22900763,
       0.89361702, 0.97465833, 0.13383002])

In [53]:
xtest4=scaler3.transform(xtest)

In [54]:
alg.fit(xtrain4,ytrain)

LinearRegression()

In [55]:
alg.score(xtrain4,ytrain)

0.7426454226803374

In [56]:
alg.score(xtest4,ytest)

0.708154552372332

In [57]:
xtest4[0]

array([0.00441691, 0.        , 0.34604106, 0.        , 0.31732777,
       0.54628195, 0.66220391, 0.21850703, 0.13043478, 0.22328244,
       0.61702128, 0.99573856, 0.23813466])