In [18]:
import tensorflow as tf

In [19]:
#constant
tf.compat.v1.disable_eager_execution()



In [24]:
#session
a=tf.constant(2)
b=tf.constant(3)
d=tf.constant([[3,3],[4,4],[5,5]])
with tf.compat.v1.Session() as sess:
    a1=tf.constant(3)
    print(a.eval())
    print((tf.transpose(d)).eval())
    print((tf.concat([d,d],axis=0)).eval())

2
[[3 4 5]
 [3 4 5]]
[[3 3]
 [4 4]
 [5 5]
 [3 3]
 [4 4]
 [5 5]]


In [38]:
#variable
a1=tf.Variable(100)
a2=tf.Variable(3)
sum=tf.add(a1,a2)
with tf.compat.v1.Session() as ses:
    ses.run(tf.compat.v1.global_variables_initializer())
    print(sum.eval())
    a1.assign(120).eval() 
    print(a1.eval())
    x=tf.compat.v1.placeholder(tf.int32)
    y=x*tf.constant(3)
    print(ses.run(y,feed_dict={x:14}))


103
120
42
